version:
  "3"

services:
  database:
    image: mysql:8.0.31
    container_name: database
    environment:
      MYSQL_DATABASE: UOUR_DB
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: dlalstjr1!
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    restart: always


  application:
    build: .
    depends_on:
      - database
    container_name: application
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/UOUR_DB?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dlalstjr1!
    volumes:
      - ./logs:/logs
      - ./images:/images
