version:
  "3"

services:
  application:
    image : minseokey/uout_test
    container_name: application
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
      - ./images:/images
