version:
  "3"

services:
  application:
    image : minseokey/uour:deploy
    container_name: application
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./logs:/logs
      - ./images:/images
