version:
  "3"

services:
  application:
    image : minseokey/uour_test:ver0.7
    container_name: application
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
      - ./images:/images
