spring:
  config:
    activate:
      on-profile: "deploy"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://uour-db.c3eg1upjelu4.ap-northeast-2.rds.amazonaws.com:3306/uour_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: dlalstjr1!

  jpa:
    hibernate:
      ddl-auto: create  #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

absolutePath: "/images"