server:
  address: localhost
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    group:
      # active properties
      "local" : "local, jwt, oauth, cloud"
    active : local
---

absolutePath: "/images"


spring:
  config:
    activate:
      on-profile: "local"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/UOUR_DB?serverTimezone=Asia/Seoul
#    username: root
#    password: dlalstjr1!

  jpa:
    hibernate:
      ddl-auto: create  #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true