jwt:
  # server secret key
  secretKey: dasfasfqwda1165213842315adasdaye52qwr65c1v58qwr55asd

  # access token
  access:
    expiration: 36000000
    header: Authorization

  # refresh token
  refresh:
    expiration: 1209600000
    header: Authroization-refresh